export const portfolioItems = [
    {
        title:"(android)네이버 부스트 코스",
        content:"",
        imageUrl:"/images/naverboost.jpg",
        images:[{image:"/images/naverboost.jpg",
                 content:"img",
                 description:"ViewPager 사용",
                 description2:"Navigationdrawer 사용",
                 description3:"Retrofit2(이미지,예매율,관람등급 서버연동)"},
                {image:"/images/naverboost2.jpg",
                content:"img",
                description:"영화상세페이지",
                description2:"Retrofit2(이미지,예매율,평점,누적관객수,줄거리 서버 연동)",
                description3:"좋아요 싫어요 버튼 구현(좋아요,싫어요 데이터 서버 연동)"},
                {image:"/images/naverboost3.jpg",
                content:"img",
                description:"ViewPager 사용",
                description2:"Retrofit2(댓글 서버연동)",
                description3:"Glide 라이브러리 사용"},
                {image:"/images/naverboost4.jpg",
                content:"img",
                description:"recyclerView 사용",
                description2:"작성하기 클릭시 댓글 작성페이지로 이동",
                description3:"신고 기능 구현"},
                {image:"/images/naverboost6.jpg",
                content:"img",
                description:"평점 기능 구현(서버와 연동)",
                description2:"평점과 텍스트 입력후 저장누르면 서버로 데이터 전송",
                description3:"취소누르면 댓글화면으로 이동"},
                {image:"/images/naverboost7.jpg",
                content:"img",
                description:"영화목록,영화API,예매하기 메뉴 구현",
                description2:"사용자설정 클릭시 개발자 메일로 문의할수있도록 구현",
                description3:"서버는 네이버에서 제공해주는 임시 Restful API 이용"},
                ],
        url:"boost"
    },
    {
        title:"(android)YoutubeProject",
        content:"",
        imageUrl: "/images/YoutubePlayerProject.jpg",
        images:[{image:"/images/youtube1.jpg",
                 content:"img",
                 description:"Youtube Data API 사용",
                 description2:"Retrofit2 사용",
                 description3:"그리드 레이아웃"},
                {image:"/images/youtube2.jpg",
                 description:"별표활성화 -> 해당동영상 즐겨찾기이동",
                 content:"img",
                 description2:"전체선택/해제 가능",
                 description3:"recyclerView 사용"},
                {image:"/images/youtube3.jpg",
                 content:"img",
                 description:"즐겨찾기 화면",
                 description2:"별표버튼클릭한 해당동영상 즐겨찾기 목록",
                 description3:"별표버튼비활성화 -> 인기순위메뉴,즐겨찾기 모두적용(Otto사용)"},
                {image:"/images/youtube5.jpg",
                 content:"img",
                 description:"재생화면",
                 description2:"상단메뉴 오른쪽버튼(반복재생활성화/비활성화 기능)",
                 description3:"X 버튼을 누르면 목록에서 삭제"}
                ],
        url:"youtubeProject"
    },
    {
        title:"(React)고객관리시스템",
        content:"",
        imageUrl: "/images/main5.png",
        images:[{image:"/images/main1.png",
                 content:"img",
                 description:"Material_UI 사용",
                 description2:"추가시 서버와 통신하여 mysql에 추가",
                 description3:"서버는 RESTful 형식으로 임시로만들어 사용"},
                {image:"/images/main2.png",
                 content:"img",
                 description:"추가시 stateRefresh",
                 description2:"변경된데이터를 가지고 리렌더링",
                 description3:"추가된 항목을 리스트에 표시"},
                {image:"/images/main3.png",
                 content:"img",
                 description:"검색기능구현",
                 description2:"filter함수와 indexOf 를사용해 구현",
                 description3:"리스트는 map함수를 이용해 구현"},
                {image:"/images/main4.png",
                 content:"img",
                 description:"삭제기능구현",
                 description2:"삭제시 stateRefresh",
                 description3:"변경된데이터를 가지고 리렌더링"},
                 {image:"/images/main5.png",
                 content:"img",
                 description:"삭제완료",
                 description2:"fetch , axios 사용(서버통신)",
                 description3:""}
                ],
        url:"management"
    },
    {
        title:"(openCv)객체인식 프로젝트",
        content:"",
        imageUrl: "/images/futsal.png",
        images:[{image:"/images/futsalVIdeo.mp4",
                 content:"video",
                 description:"RaspberryPi , OpenCv , Python 사용",
                 description2:"점수판 구현(공이 골대로 들어가면 점수판 1점씩 증가)",
                 description3:"공 객체 인식(CamShift 알고리즘에서 힌트를얻어서 구현)",
                 description4:"동영상이 완료되면 IIS FTP서버에 동영상 자동 업로드"}
                ],
        url:"futsal"
    }
]